import Head from 'next/head'

export default function Home() {
  return (
    <div className="home">
      <Head>
        <title>Next E Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold">Next Store</h1>
    </div>
  )
}
